name: Github actions CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: '0'
    - name: tag version
      uses: anothrNick/github-tag-action@1.0.0
      env:
        GITHUB_USER: ${{ secrets.GIT_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
      - name: Create a Release
        uses: elgohr/Github-Release-Action@master
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run:
          mvn clean package -DattachMuleSources -Pgithub deploy
          mvn release:update-versions -DautoVersionSubmodules=true
        env:
          GITHUB_USER: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
